### ISSUE TITLE
[Feature] Add ability to call API with pagination

### ISSUE THREAD

**Issue by udz-codes** [udz-codes/express-jwt-boilerplate#10]
1. Add an example to hit an API endpoint with GET method to fetch given number of objects.
2. Example: `GET api/products?limit=100`
3. Query the database according to the value of limit.
4. Also, set a predefined limit of 200. That means API will never fetch more than 500 objects in single request.

**Comment by Shrenik0321** [comment]
hi @udz-codes, can you assign me to this issue?

**Comment by udz-codes** [comment]
@Shrenik0321 Great, assigning it to you.

**Comment by udz-codes** [comment]
Added some requirements for this issue in PR comments https://github.com/udz-codes/express-jwt-boilerplate/pull/11#discussion_r1342571248
