### ISSUE TITLE
[Feature] Add rate limiting to prevent DDOS 

### ISSUE THREAD

**Issue by shreyashnalawade1** [udz-codes/express-jwt-boilerplate#9]
Can I submit a simple PR?

**Comment by udz-codes** [comment]
Great, I'll assign this issue to you.

**Comment by Shrenik0321** [comment]
hey @udz-codes , has there been any updates on this issue?

**Comment by udz-codes** [comment]
@shreyashnalawade1 are you going to work on this issue?

**Comment by udz-codes** [comment]
@Shrenik0321 I think I can assign it to you now, are you willing to work on this?

**Comment by Shrenik0321** [comment]
yeah would love to @udz-codes

**Comment by udz-codes** [comment]
@Shrenik0321 Great, assigning this to you. Please add this one in a separate file as another example.
